import { createClient, createRegistration } from "@/hooks/use-clients";
import { createAntenatalVisit } from "@/hooks/use-visits";
import { createAppointment } from "@/hooks/use-appointments";

export async function seedDemoData() {
  // Client 1: Active antenatal, 32 weeks
  const edd1 = new Date();
  edd1.setDate(edd1.getDate() + 56); // ~32 weeks gestation
  const c1 = await createClient({
    practitioner_id: "pending",
    nhi: "ZZB4567",
    first_name: "Aroha",
    last_name: "Te Whare",
    preferred_name: null,
    date_of_birth: "1994-06-12",
    address_line_1: "14 Revell Street",
    address_line_2: null,
    city: "Hokitika",
    postcode: "7810",
    lat: null,
    lng: null,
    phone: "027 345 6789",
    email: "aroha.tw@gmail.com",
    ethnicity: ["Maori"],
    iwi_affiliation: "Ngai Tahu",
    language: "English",
    interpreter_required: false,
    gp_name: "Dr Sarah Chen",
    gp_practice: "Hokitika Health Centre",
    gp_phone: "03 755 8100",
    emergency_contact_name: "Hemi Te Whare",
    emergency_contact_phone: "027 555 1234",
    emergency_contact_relationship: "Partner",
    notes: null,
  });
  const reg1 = await createRegistration({
    client_id: c1.id,
    practitioner_id: "pending",
    registration_date: "2025-11-15",
    agreed_edd: edd1.toISOString().split("T")[0],
    edd_method: "ultrasound",
    registration_gestation_weeks: 10,
    registration_gestation_days: 3,
    gravida: 2,
    parity: 1,
    transfer_in_from: null,
    transfer_in_date: null,
    transfer_out_to: null,
    transfer_out_date: null,
    status: "active",
    discharge_date: null,
  });
  // A couple of AN visits for Aroha
  const v1Date = new Date();
  v1Date.setDate(v1Date.getDate() - 14);
  await createAntenatalVisit({
    registration_id: reg1.id,
    practitioner_id: "pending",
    visit_date: v1Date.toISOString().split("T")[0],
    visit_time: "10:30",
    gestation_weeks: 30,
    gestation_days: 2,
    location: "Home",
    visit_type: "routine",
    bp_systolic: 118,
    bp_diastolic: 72,
    pulse: 78,
    temperature: 36.6,
    weight_kg: 74.2,
    fundal_height_cm: 30,
    presentation: "cephalic",
    position: "LOA",
    engagement: "Free",
    fetal_heart_rate: 142,
    fetal_movements: "normal",
    urine_protein: "nil",
    urine_glucose: "nil",
    oedema: "nil",
    hb_result: null,
    blood_tests_ordered: null,
    ultrasound_ordered: false,
    referrals_made: null,
    topics_discussed: ["Birth plan", "Breastfeeding"],
    plan: "Continue routine care. Next visit in 2 weeks.",
    notes: null,
    after_hours: false,
    duration_minutes: 45,
    interpreter_present: false,
    next_visit_date: new Date().toISOString().split("T")[0],
    next_visit_gestation: "32+2",
    midwife_signature: true,
  });
  await createAntenatalVisit({
    registration_id: reg1.id,
    practitioner_id: "pending",
    visit_date: new Date().toISOString().split("T")[0],
    visit_time: "14:00",
    gestation_weeks: 32,
    gestation_days: 2,
    location: "Clinic",
    visit_type: "routine",
    bp_systolic: 122,
    bp_diastolic: 76,
    pulse: 80,
    temperature: 36.5,
    weight_kg: 75.1,
    fundal_height_cm: 32,
    presentation: "cephalic",
    position: "LOA",
    engagement: "Free",
    fetal_heart_rate: 138,
    fetal_movements: "normal",
    urine_protein: "nil",
    urine_glucose: "nil",
    oedema: "mild",
    hb_result: 115,
    blood_tests_ordered: ["FBC", "Ferritin"],
    ultrasound_ordered: false,
    referrals_made: null,
    topics_discussed: ["Iron levels", "Pelvic floor"],
    plan: "Hb slightly low, commence iron supplement. Review in 2 weeks.",
    notes: null,
    after_hours: false,
    duration_minutes: 40,
    interpreter_present: false,
    next_visit_date: null,
    next_visit_gestation: "34+2",
    midwife_signature: true,
  });

  // Client 2: Active antenatal, 26 weeks, elevated BP
  const edd2 = new Date();
  edd2.setDate(edd2.getDate() + 98); // ~26 weeks
  const c2 = await createClient({
    practitioner_id: "pending",
    nhi: "ZZC7890",
    first_name: "Emma",
    last_name: "Blackwood",
    preferred_name: "Em",
    date_of_birth: "1990-02-28",
    address_line_1: "8 Weld Street",
    address_line_2: null,
    city: "Greymouth",
    postcode: "7805",
    lat: null,
    lng: null,
    phone: "021 876 5432",
    email: "emma.blackwood@outlook.co.nz",
    ethnicity: ["NZ European"],
    iwi_affiliation: null,
    language: "English",
    interpreter_required: false,
    gp_name: "Dr Mark Thompson",
    gp_practice: "Grey Base Medical",
    gp_phone: "03 768 0400",
    emergency_contact_name: "James Blackwood",
    emergency_contact_phone: "021 777 8888",
    emergency_contact_relationship: "Husband",
    notes: "Previous gestational diabetes - monitoring closely.",
  });
  const reg2 = await createRegistration({
    client_id: c2.id,
    practitioner_id: "pending",
    registration_date: "2026-01-10",
    agreed_edd: edd2.toISOString().split("T")[0],
    edd_method: "ultrasound",
    registration_gestation_weeks: 8,
    registration_gestation_days: 0,
    gravida: 3,
    parity: 2,
    transfer_in_from: null,
    transfer_in_date: null,
    transfer_out_to: null,
    transfer_out_date: null,
    status: "active",
    discharge_date: null,
  });
  // AN visit with elevated BP to trigger alert
  const v2Date = new Date();
  v2Date.setDate(v2Date.getDate() - 3);
  await createAntenatalVisit({
    registration_id: reg2.id,
    practitioner_id: "pending",
    visit_date: v2Date.toISOString().split("T")[0],
    visit_time: "09:00",
    gestation_weeks: 25,
    gestation_days: 4,
    location: "Clinic",
    visit_type: "routine",
    bp_systolic: 142,
    bp_diastolic: 92,
    pulse: 84,
    temperature: 36.7,
    weight_kg: 82.5,
    fundal_height_cm: 25,
    presentation: "cephalic",
    position: null,
    engagement: "Free",
    fetal_heart_rate: 150,
    fetal_movements: "normal",
    urine_protein: "trace",
    urine_glucose: "nil",
    oedema: "mild",
    hb_result: null,
    blood_tests_ordered: ["Pre-eclampsia bloods"],
    ultrasound_ordered: false,
    referrals_made: null,
    topics_discussed: ["BP monitoring", "Warning signs"],
    plan: "Elevated BP with trace proteinuria. Recheck in 3 days. If persists, refer to secondary care.",
    notes: "Discussed pre-eclampsia signs and when to call.",
    after_hours: false,
    duration_minutes: 50,
    interpreter_present: false,
    next_visit_date: new Date().toISOString().split("T")[0],
    next_visit_gestation: "26+0",
    midwife_signature: true,
  });

  // Client 3: Postnatal, baby 10 days old
  const c3 = await createClient({
    practitioner_id: "pending",
    nhi: "ZZD1234",
    first_name: "Mereana",
    last_name: "Parata",
    preferred_name: "Mere",
    date_of_birth: "1988-11-03",
    address_line_1: "22 Stafford Street",
    address_line_2: null,
    city: "Greymouth",
    postcode: "7805",
    lat: null,
    lng: null,
    phone: "022 123 4567",
    email: "mere.parata@gmail.com",
    ethnicity: ["Maori"],
    iwi_affiliation: "Ngati Waewae",
    language: "English",
    interpreter_required: false,
    gp_name: "Dr Sarah Chen",
    gp_practice: "Hokitika Health Centre",
    gp_phone: "03 755 8100",
    emergency_contact_name: "Tane Parata",
    emergency_contact_phone: "022 987 6543",
    emergency_contact_relationship: "Partner",
    notes: null,
  });
  const birthDate = new Date();
  birthDate.setDate(birthDate.getDate() - 10);
  const edd3 = new Date(birthDate);
  edd3.setDate(edd3.getDate() + 5); // born at 39+2
  await createRegistration({
    client_id: c3.id,
    practitioner_id: "pending",
    registration_date: "2025-08-20",
    agreed_edd: edd3.toISOString().split("T")[0],
    edd_method: "lmp",
    registration_gestation_weeks: 8,
    registration_gestation_days: 5,
    gravida: 4,
    parity: 3,
    transfer_in_from: null,
    transfer_in_date: null,
    transfer_out_to: null,
    transfer_out_date: null,
    status: "postnatal",
    discharge_date: null,
  });

  // Client 4: Early pregnancy, 14 weeks
  const edd4 = new Date();
  edd4.setDate(edd4.getDate() + 182); // ~14 weeks
  const c4 = await createClient({
    practitioner_id: "pending",
    nhi: "ZZE5678",
    first_name: "Sophie",
    last_name: "van der Berg",
    preferred_name: null,
    date_of_birth: "1997-08-22",
    address_line_1: "5 Tainui Street",
    address_line_2: null,
    city: "Hokitika",
    postcode: "7810",
    lat: null,
    lng: null,
    phone: "027 999 3456",
    email: "sophie.vdb@icloud.com",
    ethnicity: ["NZ European"],
    iwi_affiliation: null,
    language: "English",
    interpreter_required: false,
    gp_name: "Dr Mark Thompson",
    gp_practice: "Grey Base Medical",
    gp_phone: "03 768 0400",
    emergency_contact_name: "Pieter van der Berg",
    emergency_contact_phone: "027 111 2222",
    emergency_contact_relationship: "Partner",
    notes: "First pregnancy. Anxious, appreciates extra time.",
  });
  await createRegistration({
    client_id: c4.id,
    practitioner_id: "pending",
    registration_date: "2026-02-28",
    agreed_edd: edd4.toISOString().split("T")[0],
    edd_method: "ultrasound",
    registration_gestation_weeks: 12,
    registration_gestation_days: 0,
    gravida: 1,
    parity: 0,
    transfer_in_from: null,
    transfer_in_date: null,
    transfer_out_to: null,
    transfer_out_date: null,
    status: "active",
    discharge_date: null,
  });

  // Client 5: Discharged
  const c5 = await createClient({
    practitioner_id: "pending",
    nhi: "ZZF9012",
    first_name: "Jade",
    last_name: "Morrison",
    preferred_name: null,
    date_of_birth: "1992-04-15",
    address_line_1: "31 Rintoul Street",
    address_line_2: null,
    city: "Reefton",
    postcode: "7830",
    lat: null,
    lng: null,
    phone: "021 456 7890",
    email: null,
    ethnicity: ["NZ European", "Maori"],
    iwi_affiliation: null,
    language: "English",
    interpreter_required: false,
    gp_name: "Dr Sarah Chen",
    gp_practice: "Hokitika Health Centre",
    gp_phone: "03 755 8100",
    emergency_contact_name: "Lisa Morrison",
    emergency_contact_phone: "021 333 4444",
    emergency_contact_relationship: "Mother",
    notes: null,
  });
  await createRegistration({
    client_id: c5.id,
    practitioner_id: "pending",
    registration_date: "2025-03-10",
    agreed_edd: "2025-10-15",
    edd_method: "ultrasound",
    registration_gestation_weeks: 9,
    registration_gestation_days: 1,
    gravida: 2,
    parity: 1,
    transfer_in_from: null,
    transfer_in_date: null,
    transfer_out_to: null,
    transfer_out_date: null,
    status: "discharged",
    discharge_date: "2025-12-20",
  });

  // A few upcoming appointments
  const tomorrow = new Date();
  tomorrow.setDate(tomorrow.getDate() + 1);
  tomorrow.setHours(9, 0, 0, 0);

  await createAppointment({
    practitioner_id: "pending",
    client_id: c1.id,
    registration_id: reg1.id,
    appointment_datetime: tomorrow.toISOString(),
    duration_minutes: 45,
    location: "Home visit - 14 Revell St, Hokitika",
    appointment_type: "antenatal",
    status: "confirmed",
    notes: "34 week check",
    reminder_sent: false,
  });

  const dayAfter = new Date();
  dayAfter.setDate(dayAfter.getDate() + 2);
  dayAfter.setHours(10, 30, 0, 0);

  await createAppointment({
    practitioner_id: "pending",
    client_id: c2.id,
    registration_id: reg2.id,
    appointment_datetime: dayAfter.toISOString(),
    duration_minutes: 30,
    location: "Clinic",
    appointment_type: "follow_up",
    status: "scheduled",
    notes: "BP recheck",
    reminder_sent: false,
  });

  const nextWeek = new Date();
  nextWeek.setDate(nextWeek.getDate() + 5);
  nextWeek.setHours(14, 0, 0, 0);

  await createAppointment({
    practitioner_id: "pending",
    client_id: c4.id,
    registration_id: null,
    appointment_datetime: nextWeek.toISOString(),
    duration_minutes: 60,
    location: "Clinic",
    appointment_type: "antenatal",
    status: "scheduled",
    notes: "16 week visit - first detailed check",
    reminder_sent: false,
  });

  return { clients: 5, visits: 3, appointments: 3 };
}
