"use client";

import { useActionState, useEffect, useState } from "react";
import { completeEnrolment, startEnrolment, type EnrolmentStart } from "./actions";
import { FormField } from "@/components/ui/form-field";
import { FormMessage } from "@/components/ui/form-message";
import { SubmitButton } from "@/components/ui/submit-button";

export function MfaEnrol() {
  const [start, setStart] = useState<EnrolmentStart | null>(null);
  const [state, action] = useActionState(completeEnrolment, null);

  useEffect(() => {
    startEnrolment().then(setStart);
  }, []);

  if (!start) return <p className="text-sm text-warm-400 text-center">Preparing your authenticator setup...</p>;
  if ("error" in start) return <FormMessage error={start.error} />;

  return (
    <form action={action} className="bg-white rounded-[14px] border border-warm-200 p-6 space-y-4">
      <input type="hidden" name="factorId" value={start.factorId} />
      <div className="flex flex-col items-center space-y-3">
        {/* The QR code is an SVG data URL generated by the auth service for this enrolment only. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={start.qrCode} alt="QR code for your authenticator app" className="w-48 h-48" />
        <div className="text-center">
          <p className="text-xs text-warm-400 uppercase tracking-[0.05em] mb-1">Or enter this key by hand</p>
          <code className="text-xs font-mono text-warm-600 bg-warm-50 px-2 py-1 rounded-[10px] select-all">{start.secret}</code>
        </div>
      </div>
      <FormField id="code" label="Code from the app" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required placeholder="000000" />
      <FormMessage error={state?.error} />
      <SubmitButton pendingText="Checking...">Turn on</SubmitButton>
    </form>
  );
}
