"use client";

import { useActionState, useEffect, useState } from "react";
import { completeEnrolment } from "./complete-enrolment";
import type { EnrolmentStart } from "./enrolment-start";
import { startEnrolment } from "./start-enrolment";
import { FormField } from "@/components/ui/form-field";
import { FormMessage } from "@/components/ui/form-message";
import { SubmitButton } from "@/components/ui/submit-button";
import { submissionKey } from "@/components/ui/submission-key";

// The key and QR code are held in state, so a rejected code keeps the same enrolment; the
// code field itself is cleared, since each code is used once.
export function MfaEnrol() {
  const [start, setStart] = useState<EnrolmentStart | null>(null);
  const [state, action] = useActionState(completeEnrolment, null);

  useEffect(() => {
    startEnrolment()
      .then(setStart)
      .catch((e: unknown) => {
        console.error("startEnrolment failed", e);
        setStart({ error: "Could not start authenticator setup. Check your connection and reload the page." });
      });
  }, []);

  if (!start) return <p className="text-sm text-warm-400 text-center">Preparing your authenticator setup...</p>;
  if ("error" in start) return <FormMessage error={start.error} />;

  const groups = start.secret.match(/.{1,4}/g) ?? [];
  return (
    <form action={action} className="bg-white rounded-[14px] border border-warm-200 p-6 space-y-4">
      <input type="hidden" name="factorId" value={start.factorId} />
      <div className="flex flex-col items-center space-y-3 text-center">
        <p className="text-sm text-warm-700">On this phone, open the key in your authenticator app.</p>
        <a
          href={start.uri}
          className="inline-flex items-center justify-center w-full min-h-11 px-4 py-2.5 text-sm font-medium text-sage-700 bg-sage-50 border border-sage-200 rounded-[10px] active:bg-sage-100"
        >
          Open in authenticator app
        </a>
        <p className="text-sm text-warm-700 pt-2">On another device, scan this code.</p>
        {/* The QR code is an SVG data URL generated by the auth service for this enrolment only. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={start.qrCode} alt="QR code for your authenticator app" className="w-48 h-48" />
        <div>
          <p className="text-xs text-warm-400 uppercase tracking-[0.05em] mb-1">Or enter this key by hand</p>
          {/* Groups of four, spaced with margins so a copy gives the key without spaces. */}
          <code className="inline-block text-sm font-mono text-warm-800 bg-warm-50 px-2 py-1 rounded-[10px] select-all break-all">
            {groups.map((g, i) => (
              <span key={i} className={i < groups.length - 1 ? "mr-2" : undefined}>
                {g}
              </span>
            ))}
          </code>
        </div>
      </div>
      <FormField id="code" label="Code from the app" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required placeholder="000000" />
      <FormMessage key={submissionKey(state)} error={state?.error} />
      <SubmitButton pendingText="Checking...">Turn on</SubmitButton>
    </form>
  );
}
